to convert a list of numeric values into a one-dimensional NumPy 
arrayARRAY

In [1]:
import numpy as np
l1=[10, 20, 30, 40, 50]

n_arr=np.array(l1)

print("Old array -- ",l1)
print("Numpy array -- ",n_arr)


Old array --  [10, 20, 30, 40, 50]
Numpy array --  [10 20 30 40 50]


to create a 3x3 matrix with values ranging from 2 to 10

In [2]:
import numpy as np

a1=np.arange(2, 11).reshape(3, 3);

print(a1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


to append values at the end of an array

In [3]:
import numpy as np

l1=[10, 20, 30, 40, 50]
r_arr=np.random.randint(5, 11,(1,3))
newarr=np.append(l1, r_arr)
print("Random array -- ",r_arr)
print("Appended array -- ",newarr)




Random array --  [[ 7 10 10]]
Appended array --  [10 20 30 40 50  7 10 10]


to create another shape from an array without changing its data(3x2 
to 2x3)

In [4]:
import numpy as np

arr1=np.random.randint(1,10,(3, 2))
print(arr1)
a1=arr1.reshape(2, 3);
print("\n",a1)




[[4 2]
 [5 4]
 [4 1]]

 [[4 2 5]
 [4 4 1]]
